# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Learning-PySpark',
                'doc_host': 'https://opedromartins.github.io',
                'git_url': 'https://github.com/opedromartins/Learning-PySpark',
                'lib_path': 'Learning_PySpark'},
  'syms': {'Learning_PySpark.core': {'Learning_PySpark.core.foo': ('core.html#foo', 'Learning_PySpark/core.py')}}}
